// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PostgresEfExample;

#nullable disable

namespace samplenpgsql.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PostgresEfExample.Contractor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATED");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("DELETED");

                    b.Property<int>("Inn")
                        .HasColumnType("integer")
                        .HasColumnName("INN");

                    b.Property<long>("L")
                        .HasColumnType("bigint")
                        .HasColumnName("L");

                    b.Property<string>("LongData")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("LONG_DATA");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NAME");

                    b.Property<uint>("version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Created")
                        .HasDatabaseName("IX_CONTRACTORS_CREATED");

                    b.HasIndex("Deleted")
                        .HasDatabaseName("IX_CONTRACTORS_DELETED");

                    b.HasIndex("Inn")
                        .HasDatabaseName("IX_CONTRACTORS_INN");

                    b.HasIndex("L")
                        .HasDatabaseName("IX_CONTRACTORS_L");

                    b.HasIndex("LongData")
                        .HasDatabaseName("IX_CONTRACTORS_LONGDATA")
                        .HasFilter("CHAR_LENGTH(\"LONG_DATA\") > 0");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_CONTRACTORS_NAME");

                    b.ToTable("CONTRACTORS", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
